export type RouteAllowlist = ReadonlyArray<readonly [method: string, pattern: string]>;

const SESSION_ROUTE_ALLOWLIST: RouteAllowlist = [
  ["GET", "/api/sessions"],
  ["POST", "/api/sessions"],
  ["DELETE", "/api/sessions"],
  ["GET", "/api/sessions/:sessionId"],
  ["DELETE", "/api/sessions/:sessionId"],
  ["GET", "/api/sessions/:sessionId/events"],
  ["GET", "/api/sessions/:sessionId/clone-token"],
  ["GET", "/api/sessions/:sessionId/ws"],
  ["GET", "/api/sessions/:sessionId/prompts"],
  ["POST", "/api/sessions/:sessionId/prompts"],
  ["POST", "/api/sessions/:sessionId/send"],
  ["POST", "/api/sessions/:sessionId/stop"],
  ["POST", "/api/sessions/:sessionId/respond"],
  ["GET", "/api/sessions/:sessionId/usage"],
  ["GET", "/api/sessions/:sessionId/input-composition"],
  ["POST", "/api/sessions/:sessionId/warm"],
  ["POST", "/api/sessions/:sessionId/retry"],
  ["POST", "/api/sessions/:sessionId/resume"],
  ["GET", "/api/sessions/:sessionId/events/history"],
  ["GET", "/api/sessions/:sessionId/context"],
  ["GET", "/api/sessions/:sessionId/export"],
  ["PUT", "/api/sessions/:sessionId/repo"],
  ["GET", "/api/sessions/:sessionId/files"],
  ["GET", "/api/sessions/:sessionId/feedback"],
  ["POST", "/api/sessions/:sessionId/feedback"],
  ["GET", "/api/sessions/:sessionId/memory-feedback"],
  ["POST", "/api/sessions/:sessionId/memory-feedback"],
  ["POST", "/api/sessions/:sessionId/artifacts"],
  ["POST", "/api/sessions/:sessionId/child-sessions"],
  ["GET", "/api/sessions/:sessionId/child-sessions"],
  ["GET", "/api/sessions/:sessionId/child-sessions/:childSessionId/status"],
];

const SHARED_READONLY_SERVICE_ROUTE_ALLOWLIST: RouteAllowlist = [
  ["GET", "/api/models"],
  ["GET", "/api/sessions/:sessionId/telemetry"],
  ["GET", "/api/sessions/:sessionId/sandbox-state"],
  ["GET", "/api/sessions/:sessionId/artifacts/list"],
  ["GET", "/api/sessions/:sessionId/feedback/all"],
  ["GET", "/api/observability/runs"],
  ["GET", "/api/observability/sessions"],
  ["GET", "/api/integrations/debug"],
  ["GET", "/api/integrations/debug/:integrationId"],
];

export const ADMIN_TOKEN_ROUTE_ALLOWLIST: RouteAllowlist = [
  ...SESSION_ROUTE_ALLOWLIST,
  ["GET", "/api/health/warm"],
  ["GET", "/api/health/schema"],
  ["POST", "/api/internal/slack/workspaces/seed"],
  ["POST", "/api/internal/qa/seed"],
  ["GET", "/api/internal/qa/integration-health"],
  ["POST", "/api/businesses"],
  ["POST", "/api/admin/businesses/:businessId/offboard"],
  ["GET", "/api/businesses/:id"],
  ["PUT", "/api/businesses/:id"],
  ["GET", "/api/businesses/:id/egress-allowlist/source"],
  ["PUT", "/api/businesses/:id/egress-allowlist/source"],
  ["POST", "/api/businesses/:id/egress-allowlist/pull-request"],
  ["POST", "/api/businesses/:id/egress-allowlist/sync"],
  ["GET", "/api/businesses/:id/integrations"],
  ["GET", "/api/integrations/me"],
  ["GET", "/api/sessions/:sessionId/integrations"],
  ["PUT", "/api/businesses/:id/integrations/:integrationId"],
  ["DELETE", "/api/businesses/:id/integrations/linear/workspace"],
  ["PUT", "/api/businesses/:id/integrations/:integrationId/credentials"],
  ["DELETE", "/api/businesses/:id/integrations/:integrationId/credentials"],
  ["POST", "/api/businesses/:businessId/repos/:owner/:repo/sandbox-layer/build-requests"],
  ["GET", "/api/businesses/:businessId/sandbox-layer/build-requests/:buildId"],
  ["GET", "/api/businesses/:businessId/sandbox-layer/build-requests/:buildId/logs"],
  ["GET", "/api/businesses/:businessId/repos/:owner/:name/test-credentials"],
  ["PUT", "/api/businesses/:businessId/repos/:owner/:name/test-credentials/:credName"],
  ["DELETE", "/api/businesses/:businessId/repos/:owner/:name/test-credentials/:credName"],
  ["GET", "/api/admin/memory-review"],
  ["GET", "/api/admin/memory-review/:id"],
  ["POST", "/api/admin/memory-review/:id/resolve"],
  ["POST", "/api/admin/memory-review/reconcile"],
  ["GET", "/api/admin/slack-channel-intake"],
  ["GET", "/api/admin/slack-channel-intake/channels"],
  ["POST", "/api/admin/slack-channel-intake"],
  ["POST", "/api/admin/sandbox-base-templates/register"],
  ["GET", "/api/admin/sandbox-base-templates/current"],
  ["POST", "/api/admin/fsm/backfill"],
  ["POST", "/api/admin/fsm/row7-repair"],
  ["POST", "/api/admin/fsm/parity-check"],
  // Outcome-truth harm ranking (admin ops only).
  ["GET", "/api/observability/session-outcomes"],
  ...SHARED_READONLY_SERVICE_ROUTE_ALLOWLIST,
];

export const CI_AUTOMATION_TOKEN_ROUTE_ALLOWLIST: RouteAllowlist = [
  ["GET", "/api/health/warm"],
  ["GET", "/api/health/schema"],
  ["POST", "/api/admin/sandbox-base-templates/register"],
  ["GET", "/api/admin/sandbox-base-templates/current"],
  ["POST", "/api/admin/fsm/row7-repair"],
  ["POST", "/api/admin/fsm/parity-check"],
];
