export const CYCLOID_DYNAMIC_TOOL_NAMESPACE = "cycloid";
export const REVIEW_LOOP_REPLY_DYNAMIC_TOOL_NAME = "review_loop_reply";
export const CYCLOID_REVIEW_LOOP_REPLY_TOOL_ID = `${CYCLOID_DYNAMIC_TOOL_NAMESPACE}.${REVIEW_LOOP_REPLY_DYNAMIC_TOOL_NAME}`;
