INSERT OR IGNORE INTO automation_rules (
  id,
  business_id,
  configured_by_user_id,
  name,
  trigger_kind,
  trigger_provider,
  slack_team_id,
  slack_channel_id,
  slack_bot_user_id,
  allowed_slack_app_ids_json,
  allowed_slack_bot_ids_json,
  repo_owner,
  repo_name,
  installation_id,
  prompt_template,
  enabled,
  created_at,
  updated_at
) VALUES
  (
    'internal-datadog-slack-alerts',
    '295d2abc-d10b-4662-b84d-7bfa66242882',
    NULL,
    'Internal Datadog Slack alerts',
    'slack_channel_message',
    'datadog',
    'T_INTERNAL',
    'C_INTERNAL_DATADOG_ALERTS',
    NULL,
    '["A_DATADOG"]',
    '["B_DATADOG"]',
    'tryarcanist',
    'arcanist',
    0,
    'Investigate this Datadog alert. Determine likely cause, gather relevant logs or traces, and propose the smallest safe fix.',
    0,
    1781880000000,
    1781880000000
  ),
  (
    'internal-sentry-slack-alerts',
    '295d2abc-d10b-4662-b84d-7bfa66242882',
    NULL,
    'Internal Sentry Slack alerts',
    'slack_channel_message',
    'sentry',
    'T_INTERNAL',
    'C_INTERNAL_SENTRY_ALERTS',
    NULL,
    '["A_SENTRY"]',
    '["B_SENTRY"]',
    'tryarcanist',
    'arcanist',
    0,
    'Investigate this Sentry alert. Determine likely cause, gather related errors or traces, and propose the smallest safe fix.',
    0,
    1781880000000,
    1781880000000
  );
