export const OFFBOARDING_USER_ID_TABLES = [
  { table: "auth_sessions", column: "user_id" },
  { table: "cli_tokens", column: "user_id" },
  { table: "github_installation_repositories_cache", column: "user_id" },
  { table: "idempotency_keys", column: "owner_user_id" },
  { table: "impersonation_sessions", column: "actor_user_id" },
  { table: "impersonation_sessions", column: "target_user_id" },
  { table: "jira_oauth_pending", column: "user_id" },
  { table: "jira_user_sites", column: "user_id" },
  { table: "slack_link_token_consumptions", column: "consumed_by_user_id" },
  { table: "slack_workspaces", column: "installed_by_user_id" },
  { table: "user_integrations", column: "user_id" },
  { table: "user_pr_review_bot_settings", column: "user_id" },
  { table: "user_settings", column: "user_id" },
] as const;

export const OFFBOARDING_SESSION_ID_TABLES = [
  { table: "automation_slot_jobs", column: "session_id" },
  { table: "child_session_limit_reservations", column: "child_session_id" },
  { table: "child_session_limit_reservations", column: "parent_session_id" },
  { table: "durable_event_replay_metadata", column: "session_id" },
  { table: "integration_lifecycle_events", column: "session_id" },
  { table: "jira_issue_session_refs", column: "session_id" },
  { table: "linear_issue_session_refs", column: "session_id" },
  { table: "linear_webhook_bootstrap_jobs", column: "session_id" },
  { table: "memory_feedback", column: "session_id" },
  { table: "memory_pr_tracking", column: "source_session_id" },
  { table: "memory_review_bot_item_results", column: "session_id" },
  { table: "memory_review_bot_recall_results", column: "session_id" },
  { table: "memory_review_bot_runs", column: "session_id" },
  { table: "memory_usage_events", column: "session_id" },
  { table: "mcp_tool_usage_events", column: "session_id" },
  { table: "openai_gateway_ledger", column: "session_id" },
  { table: "openai_gateway_session_tokens", column: "session_id" },
  { table: "pr_activity_events", column: "session_id" },
  { table: "pr_takeover_admission_claims", column: "session_id" },
  { table: "pr_coordination", column: "session_id" },
  { table: "pr_coordination_events", column: "session_id" },
  { table: "pr_review_item_dispositions", column: "session_id" },
  { table: "pr_review_response_epochs", column: "session_id" },
  { table: "pr_review_response_operations", column: "session_id" },
  { table: "pr_review_reviewer_settle", column: "session_id" },
  { table: "pr_review_status_comments", column: "session_id" },
  { table: "pr_stage_regions", column: "owning_session_id" },
  { table: "prompt_runs", column: "session_id" },
  { table: "prompt_tool_rollup", column: "session_id" },
  { table: "runtime_capacity_admissions", column: "session_id" },
  { table: "session_completions", column: "session_id" },
  { table: "session_evaluations", column: "session_id" },
  { table: "session_feedback", column: "session_id" },
  { table: "session_memory_usage", column: "session_id" },
  { table: "session_outcomes", column: "session_id" },
  { table: "session_pr_metadata", column: "session_id" },
  { table: "session_webhook_refs", column: "session_id" },
  { table: "slack_posts", column: "session_id" },
  { table: "slack_pr_merged_posts", column: "session_id" },
  { table: "slack_interaction_requests", column: "session_id" },
  { table: "slack_thread_session_refs", column: "session_id" },
] as const;

export const OFFBOARDING_ROOT_TABLES = ["session_index", "business_members", "users", "businesses"] as const;

const SKIPPED_TABLES: Record<string, string> = {
  _cf_METADATA: "Cloudflare local metadata table",
  cron_sweep_cursors: "global scheduled job cursor state",
  d1_migrations: "D1 migration bookkeeping",
  env_blob_repos: "repo index for env blobs; env_blobs owns business deletion",
  github_installations: "GitHub app installations are org/user scoped, not business scoped",
  managed_pr_comments: "repo/PR keyed coordination cache without business ownership",
  memory_analysis_jobs: "review-job keyed historical analysis queue without business ownership",
  memory_facts_fts: "SQLite FTS shadow table for memory_facts",
  memory_facts_fts_config: "SQLite FTS shadow table for memory_facts",
  memory_facts_fts_data: "SQLite FTS shadow table for memory_facts",
  memory_facts_fts_docsize: "SQLite FTS shadow table for memory_facts",
  memory_facts_fts_idx: "SQLite FTS shadow table for memory_facts",
  memory_takes_fts: "SQLite FTS shadow table for memory_takes",
  memory_takes_fts_config: "SQLite FTS shadow table for memory_takes",
  memory_takes_fts_data: "SQLite FTS shadow table for memory_takes",
  memory_takes_fts_docsize: "SQLite FTS shadow table for memory_takes",
  memory_takes_fts_idx: "SQLite FTS shadow table for memory_takes",
  offboarding_jobs: "offboarding audit/resume manifests are retained after purge",
  pending_signups: "global unauthenticated signup queue",
  pr_body_documents: "repo/PR keyed GitHub body cache without business ownership",
  pr_body_locks: "repo/PR keyed GitHub body lock without business ownership",
  pr_body_regions: "repo/PR keyed GitHub body cache without business ownership",
  repo_memories: "repo keyed memory copy; canonical business memory rows are deleted separately",
  repo_memory_judgments: "repo keyed historical memory judgment output",
  sandbox_base_templates: "global runtime template registry",
  sandbox_layer_active_artifacts: "source-keyed artifact pointer; source row owns business deletion",
  sandbox_layer_artifacts: "source/build-keyed artifact history; source row owns business deletion",
  sandbox_layer_build_log_chunks: "build-keyed logs; source/build rows own business deletion",
  sandbox_layer_builds: "source-keyed build history; source row owns business deletion",
  sandbox_layer_rebuild_campaign_items: "campaign/source-keyed rows; campaign/source rows own business deletion",
  slack_repo_disambiguations: "short-lived Slack chooser state keyed by channel/thread, not durable business data",
  webhook_idempotency: "global webhook replay guard",
};

const TIER_MANAGED_TABLE_NAMES = new Set<string>([
  ...OFFBOARDING_USER_ID_TABLES.map(({ table }) => table),
  ...OFFBOARDING_SESSION_ID_TABLES.map(({ table }) => table),
  ...OFFBOARDING_ROOT_TABLES,
]);

export const OFFBOARDING_DYNAMIC_BUSINESS_ID_EXCLUDED_TABLES = new Set<string>([
  ...TIER_MANAGED_TABLE_NAMES,
  ...Object.keys(SKIPPED_TABLES),
]);
