#!/usr/bin/env bash
# Build the Cycloid security package — single consolidated docx.
#
# Usage:
#   docs/non-technical-docs/security/_template/build.sh [output_dir]
#
# Defaults to ./dist/ inside docs/non-technical-docs/security/. The pipeline runs pandoc
# with the Cycloid reference docx, which is a hybrid of (a) pandoc's default
# style set (so tables, TOC, and headings render correctly) and (b) the
# Cycloid letterhead's header (logo) and footer (address + confidentiality
# marker). The reference doc is committed at _template/cycloid_reference.docx
# and is regenerated by build-reference.sh.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PACKAGE_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"
SOURCE="${PACKAGE_DIR}/source/cycloid-security-package.md"
REFERENCE="${SCRIPT_DIR}/cycloid_reference.docx"
OUTPUT_DIR="${1:-${PACKAGE_DIR}/dist}"
OUTPUT="${OUTPUT_DIR}/cycloid-security-package.docx"

if ! command -v pandoc >/dev/null 2>&1; then
  echo "error: pandoc not found in PATH" >&2
  exit 1
fi

for path in "${SOURCE}" "${REFERENCE}"; do
  if [[ ! -f "${path}" ]]; then
    echo "error: missing input ${path}" >&2
    exit 1
  fi
done

mkdir -p "${OUTPUT_DIR}"

pandoc "${SOURCE}" \
  --from=markdown+pipe_tables+yaml_metadata_block \
  --to=docx \
  --toc \
  --toc-depth=2 \
  --reference-doc="${REFERENCE}" \
  --output="${OUTPUT}"

# Post-process the docx to make tables paginate cleanly in Pages and Word.
#
# Pandoc emits every table with <w:tblLayout w:type="fixed"/>. Pages treats
# that as "keep this table together on one page": when a heading sits above
# the table and the table doesn't fit the remaining space, Pages orphans
# the heading and pushes the whole table to the next page, leaving a large
# blank. Stripping the directive switches the table to auto layout, which
# Pages and Word both split row-by-row across page breaks as expected.
python3 - "${OUTPUT}" <<'PY'
import sys, zipfile, re

path = sys.argv[1]
with zipfile.ZipFile(path) as zin:
    items = []
    for info in zin.infolist():
        data = zin.read(info.filename)
        if info.filename == "word/document.xml":
            text = data.decode("utf-8")
            text = re.sub(r'<w:tblLayout\s[^/]*/>', '', text)
            data = text.encode("utf-8")
        items.append((info, data))

with zipfile.ZipFile(path, "w", zipfile.ZIP_DEFLATED) as zout:
    for info, data in items:
        zout.writestr(info, data)
PY

echo "Built ${OUTPUT}"
