import type { SandboxLayerInstruction } from "./layer-parser";

const RESERVED_EXACT_ENV_NAMES = new Set([
  "SESSION_ID",
  "CONTROL_PLANE_URL",
  "REPO_OWNER",
  "REPO_NAME",
  "PATH",
  "HOME",
  "USER",
  "SHELL",
]);

const RESERVED_ENV_PREFIXES = [
  "ARCANIST_",
  "SANDBOX_",
  "GITHUB_",
  "OPENAI_",
  "ANTHROPIC_",
  "E2B_",
  "CODEX_",
  "CLAUDE_",
];

export function quoteShell(value: string): string {
  return `'${value.replace(/'/g, `'\\''`)}'`;
}

export function assertSandboxLayerEnvKeyAllowed(key: string): void {
  if (RESERVED_EXACT_ENV_NAMES.has(key) || RESERVED_ENV_PREFIXES.some((prefix) => key.startsWith(prefix))) {
    throw new Error(`ENV key '${key}' is reserved`);
  }
}

export function compileSandboxLayerEnvInstruction(values: Record<string, string>): string {
  const lines = Object.entries(values)
    .sort(([a], [b]) => a.localeCompare(b))
    .map(([key, value]) => {
      assertSandboxLayerEnvKeyAllowed(key);
      return `export ${key}=${quoteShell(value)}`;
    });
  const payload = [
    "# Generated by Cycloid sandbox layer compiler. Do not edit.",
    "export ARCANIST_SANDBOX_LAYER_ENV=1",
    ...lines,
    "",
  ].join("\n");
  return [
    "install -d -m 0755 /etc/cycloid /etc/profile.d",
    "cat > /etc/cycloid/layer-env.sh <<'EOF'",
    payload,
    "EOF",
    "chown root:root /etc/cycloid/layer-env.sh",
    "chmod 0644 /etc/cycloid/layer-env.sh",
    "cat > /etc/profile.d/cycloid-layer-env.sh <<'EOF'",
    "# Generated by Cycloid sandbox layer compiler. Do not edit.",
    "if [ -r /etc/cycloid/layer-env.sh ]; then",
    "  . /etc/cycloid/layer-env.sh",
    "fi",
    "EOF",
    "chown root:root /etc/profile.d/cycloid-layer-env.sh",
    "chmod 0644 /etc/profile.d/cycloid-layer-env.sh",
  ].join("\n");
}

export function compileSandboxLayerSmokeCommand(command: string[]): string {
  return command.map(quoteShell).join(" ");
}

export function compileSandboxLayerBuildCommands(instructions: SandboxLayerInstruction[]): string[] {
  const commands: string[] = [compileSandboxLayerEnvInstruction({})];
  const accumulatedEnv: Record<string, string> = {};
  for (const instruction of instructions) {
    if (instruction.kind === "run") {
      commands.push(instruction.command);
    } else {
      Object.assign(accumulatedEnv, instruction.values);
      commands.push(compileSandboxLayerEnvInstruction(accumulatedEnv));
    }
  }
  return commands;
}
